# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SupermetricsCli < Formula
  desc "Command-line interface for the Supermetrics API"
  homepage "https://github.com/supermetrics-public/supermetrics-cli"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/supermetrics-public/supermetrics-cli/releases/download/v0.0.7/supermetrics-cli_0.0.7_darwin_amd64.tar.gz"
      sha256 "97b634eb993b2f02da7b32b6d4c27200e642586088dcb29ce4bc46b82ab2c180"

      define_method(:install) do
        bin.install "supermetrics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/supermetrics-public/supermetrics-cli/releases/download/v0.0.7/supermetrics-cli_0.0.7_darwin_arm64.tar.gz"
      sha256 "fd580b1efee02e7067444f8b0316707526484901820866f86cc08677cdfec285"

      define_method(:install) do
        bin.install "supermetrics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermetrics-public/supermetrics-cli/releases/download/v0.0.7/supermetrics-cli_0.0.7_linux_amd64.tar.gz"
      sha256 "1e2897413d35b8b1a1d095d3b236ae544522e8259b9e2a2969fc4ea65078394b"
      define_method(:install) do
        bin.install "supermetrics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermetrics-public/supermetrics-cli/releases/download/v0.0.7/supermetrics-cli_0.0.7_linux_arm64.tar.gz"
      sha256 "0792f56625db99948aff1af581efaa955b1c718b8a279a9ce9eaf550d5a3b576"
      define_method(:install) do
        bin.install "supermetrics"
      end
    end
  end

  test do
    system "#{bin}/supermetrics", "version"
  end
end
